
# 不要让异常逃离析构函数
- 有这么一种情况
``` cpp
class test
{
public:
    test():ptr_num(new int(100)){}
    void close(){ throw 1; }
    ~test() 
    {
        delete ptr_num;
        cout << "in destructors!" << endl;
        close();
        cout << "out destructors!" << endl;
    }
int* ptr_num;
};

int main(void)
{
    try
    {
        test tlist[5];
    }
    catch (int& num)
    {
        cout << num << endl;
    }
    catch (...)
    {
        cout << "..." << endl;
        std::abort();       //结束进程
    }
    getchar();
    return 0;
}
```
- tlist中有5个元素，如果异常不在析构里面就进行处理的话，一旦跳出，其它4个元素的析构函数将不会被调用，这样其它4个元素的ptr_num的内存是没有被释放的
- 尽量使用以下方式进行处理
``` cpp

class test
{
public:
    test():ptr_num(new int(100)){}
    void close(){ throw 1; }
    ~test() 
    {
        try
        {
            delete ptr_num;
            cout << "in destructors!" << endl;
            close();
            cout << "out destructors!" << endl;
        }
        catch (int& num)
        {
            cout << num << endl;
        }
        catch (...)
        {
            cout << "..." << endl;
        }
    }
int* ptr_num;
};

int main(void)
{
    {
        test tlist[5];
    }
    getchar();
    return 0;
}
```